language: node_js

node_js: stable

cache:
    directories:
    - node_modules

install:
    - npm install

script:
    - hexo clean
    - hexo g

after_script:
    - cd ./public
    - git init
    - git config user.name "adiao3210"
    - git config user.email "2056079548@qq.com"
    - git add .
    - git commit -m "代码是自动部署的哈"
    - git push --force --quiet "https://${adiao3210}@${GH_REF}" main:gh-pages

branches:
    only:
        - main

env:
  global:
        - GH_REF: github.com/adiao321/adiao3210.git